version: "3"

services:
    web:
        build:
            context: .
            dockerfile: ./dockerfile
        environment:
            XDEBUG_CONFIG: remote_host=192.168.1.53 remote_port=9000 remote_enable=1 remote_log=/tmp/xdebuglogs
        ports:
            - '80:80'
        volumes:
            - './web:/var/www/html'